


# Database

spring.datasource.url=jdbc:mysql://localhost:3306/sprms_db
spring.datasource.username=root
spring.datasource.password=subarts
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.file.name=logs/SPRMS.log
