spring.application.name=sprms


# Profile
spring.profiles.active=dev

#context path
server.servlet.context-path=/

# Server
server.port=8080
#server.servlet.context-path=/FLDMGT/
server.servlet.context-path=


# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.file.name=logs/SPRMS-app.log

# Maximum file size
spring.servlet.multipart.max-file-size=50MB

# Maximum request size (sum of all files)
spring.servlet.multipart.max-request-size=50MB

#upload directory
app.upload.dir=uploads/images/


